# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

POST http://127.0.0.1:8000/v1/chat
Accept: application/json

{
    "question": "What is the GitLab engineering handbook?",
    "llm": "gemini",
    "model": "gemini-1.5-pro",
    "temp": 0.7
}
